services:
  - type: web
    name: sensor-1
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: sensor-2
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: CONTROL_URL
        value:  https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: sensor-3
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: CONTROL_URL
        value:  https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: sensor-4
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: control
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
