services:
  - type: web
    name: control
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./control/Dockerfile
    dockerContext: ./control
    envVars:
      - key: SERVER_ID
        value: CONTROL_SERVER
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
        
  - type: web
    name: EERON
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_1
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: TSLI
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_2
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: KIGS
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_3
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false


  - type: web
    name: BIGF
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_4
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
