services:
  - type: web
    name: control
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./control/Dockerfile
    dockerContext: ./control
    envVars:
      - key: SERVER_ID
        value: CONTROL_SERVER
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
        
  - type: web
    name: sensor-1
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_1
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: sensor-2
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_2
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false

  - type: web
    name: sensor-3
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_3
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false


  - type: web
    name: sensor-4
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: ./sensor/Dockerfile
    dockerContext: ./sensor
    envVars:
      - key: SERVER_ID
        value: SERVER_4
      - key: CONTROL_URL
        value: https://control-jo9v.onrender.com
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
